#Hugo configuration
title = "qewrsdg"
baseURL = "https:\/\/qwe.sdfgv.fd"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true
galleryChannelIds = ""

[params]
loginId = "1758823"
subfolder = ""
firstpartycookies = true
cookiedomain = "sdfgv.fd"
